"use strict";
exports.__esModule = true;
exports.UsLotteryPrizes = void 0;
var UsLotteryPrizes;
(function (UsLotteryPrizes) {
    UsLotteryPrizes["cashThreeStraight"] = "cashThreeStraight";
    UsLotteryPrizes["cashThreeStraightDoubles"] = "cashThreeStraightDoubles";
    UsLotteryPrizes["playFourStraight"] = "playFourStraight";
    UsLotteryPrizes["pickFiveStraight"] = "pickFiveStraight";
    UsLotteryPrizes["cashThreeBoxThreeWay"] = "cashThreeBoxThreeWay";
    UsLotteryPrizes["cashThreeBoxSixWay"] = "cashThreeBoxSixWay";
    UsLotteryPrizes["playFourBoxFourWay"] = "playFourBoxFourWay";
    UsLotteryPrizes["playFourBoxSixWay"] = "playFourBoxSixWay";
    UsLotteryPrizes["playFourBoxTwelfthWay"] = "playFourBoxTwelfthWay";
    UsLotteryPrizes["playFourBoxTwentyFourthWay"] = "playFourBoxTwentyFourthWay";
    UsLotteryPrizes["pickFiveBoxFifthWay"] = "pickFiveBoxFifthWay";
    UsLotteryPrizes["pickFiveBoxTenthWay"] = "pickFiveBoxTenthWay";
    UsLotteryPrizes["pickFiveBoxTwentiethWay"] = "pickFiveBoxTwentiethWay";
    UsLotteryPrizes["pickFiveBoxThirtiethWay"] = "pickFiveBoxThirtiethWay";
    UsLotteryPrizes["pickFiveBoxSixtiethWay"] = "pickFiveBoxSixtiethWay";
    UsLotteryPrizes["pickFiveBoxOneHundredTwentiethWay"] = "pickFiveBoxOneHundredTwentiethWay";
})(UsLotteryPrizes = exports.UsLotteryPrizes || (exports.UsLotteryPrizes = {}));
