export enum UsLotteryPrizes {
  cashThreeStraight = 'cashThreeStraight',
  cashThreeStraightDoubles = 'cashThreeStraightDoubles',
  playFourStraight = 'playFourStraight',
  pickFiveStraight = 'pickFiveStraight',
  cashThreeBoxThreeWay = 'cashThreeBoxThreeWay',
  cashThreeBoxSixWay = 'cashThreeBoxSixWay',
  playFourBoxFourWay = 'playFourBoxFourWay',
  playFourBoxSixWay = 'playFourBoxSixWay',
  playFourBoxTwelfthWay = 'playFourBoxTwelfthWay',
  playFourBoxTwentyFourthWay = 'playFourBoxTwentyFourthWay',
  pickFiveBoxFifthWay = 'pickFiveBoxFifthWay',
  pickFiveBoxTenthWay = 'pickFiveBoxTenthWay',
  pickFiveBoxTwentiethWay = 'pickFiveBoxTwentiethWay',
  pickFiveBoxThirtiethWay = 'pickFiveBoxThirtiethWay',
  pickFiveBoxSixtiethWay = 'pickFiveBoxSixtiethWay',
  pickFiveBoxOneHundredTwentiethWay = 'pickFiveBoxOneHundredTwentiethWay',
}
